"""Teacher-forced training loop, reproducibility manifest, and diagnostics."""
from world_model.training.diagnostics import (
    CollapseReport,
    collapse_diagnostics,
    effective_rank,
    mean_feature_std,
    relative_spread,
    retrieval_accuracy,
)
from world_model.training.loop import (
    OVERFIT_LOSS_THRESHOLD,
    OVERFIT_RANK_THRESHOLD,
    OVERFIT_RETRIEVAL_THRESHOLD,
    OVERFIT_SPREAD_THRESHOLD,
    OverfitReport,
    StepResult,
    TeacherForcedTrainer,
    TrainingConfig,
    build_window_loader,
    resize_transform,
    run_overfit,
    seed_all,
    select_diverse_windows,
    select_motion_windows,
)
from world_model.training.manifest import (
    MANIFEST_VERSION,
    RunManifest,
    RunManifestPayload,
    capture_environment,
    git_revision,
)

__all__ = [
    "CollapseReport",
    "MANIFEST_VERSION",
    "OVERFIT_LOSS_THRESHOLD",
    "OVERFIT_RANK_THRESHOLD",
    "OVERFIT_RETRIEVAL_THRESHOLD",
    "OVERFIT_SPREAD_THRESHOLD",
    "OverfitReport",
    "RunManifest",
    "RunManifestPayload",
    "StepResult",
    "TeacherForcedTrainer",
    "TrainingConfig",
    "build_window_loader",
    "capture_environment",
    "collapse_diagnostics",
    "effective_rank",
    "git_revision",
    "mean_feature_std",
    "relative_spread",
    "resize_transform",
    "retrieval_accuracy",
    "run_overfit",
    "seed_all",
    "select_diverse_windows",
    "select_motion_windows",
]
